# Generated by Django 3.2.6 on 2021-08-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0004_alter_crewmember_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Runs_on',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.theatre')),
            ],
        ),
    ]
