# Generated by Django 3.2.6 on 2021-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs_on',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='street',
            field=models.CharField(default='stree_name', max_length=256),
        ),
    ]
