# Generated by Django 3.2.6 on 2021-08-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_crewmember_unique_together'),
        ('theatres', '0002_auto_20210824_1948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='runs_on',
            unique_together={('theatre', 'movie')},
        ),
    ]
