# Generated by Django 3.2.6 on 2021-08-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_crewmember_unique_together'),
        ('theatres', '0003_alter_runs_on_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='show_time',
        ),
        migrations.AlterUniqueTogether(
            name='runs_on',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='English', max_length=100)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='runs_on',
            name='language',
        ),
        migrations.RemoveField(
            model_name='runs_on',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='runs_on',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='runs_on',
            name='show_time',
        ),
        migrations.AddField(
            model_name='runs_on',
            name='show',
            field=models.ManyToManyField(to='theatres.Show'),
        ),
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='theatres.show'),
        ),
    ]
