# Generated by Django 3.2.6 on 2021-08-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0004_auto_20210825_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runs_on',
            old_name='show',
            new_name='shows',
        ),
    ]
