# Generated by Django 3.2.6 on 2021-08-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0005_rename_show_runs_on_shows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='price',
        ),
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
