# Generated by Django 3.2.6 on 2021-08-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0006_auto_20210826_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
