# Generated by Django 3.2.6 on 2021-08-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatres', '0007_delete_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_code', models.CharField(max_length=10)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.show')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=256)),
                ('booking_time', models.DateTimeField()),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.seat')),
            ],
        ),
    ]
