# Generated by Django 3.2.6 on 2021-08-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_ticket_booking_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('seat_code', 'theatre', 'show'), name='Seat for a show'),
        ),
    ]
