# Generated by Django 3.2.6 on 2021-08-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_ticket_seat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seats',
            field=models.ManyToManyField(to='bookings.Seat'),
        ),
    ]
