# Generated by Django 3.2.6 on 2021-08-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210823_1758'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crewmember',
            unique_together={('person', 'movie')},
        ),
    ]
